@startuml
entity Cities{
    name: varchar
    latitude: numeric 
    longitude: numeric
}
entity Sellers{
    name: int
    phone: varchar
}
entity Buyers{
    name: int
    phone: varchar
}
entity Ads{
    title: varchar
    date: date
}
entity Cars{
    brand: varchar
    model: varchar
    type: varchar
    year: int
    price: int
}
entity Bids{
    date: date
    price: int
    status: enum
}
@enduml
